### ISSUE TITLE
Wrong implementation for hsv2rgb

### ISSUE THREAD

**Issue by 599316527** [jonathantneal/convert-colors#2]
## Expected

```js
expect( hsv2rgb(123, 37, 60) ).toEqual( [96, 153, 99].map(val => val / 255 * 100) )
```

![53f1c857c8d2487914eaaf3d7](https://user-images.githubusercontent.com/1331413/52034664-d9592980-2563-11e9-8fc6-845cc75f83aa.png)

## Actual

```js
Expected value to equal:
      [37.64705882352941, 60, 38.82352941176471]
Received:
      [37.8, 60, 127.71]
```

## Why

https://github.com/jonathantneal/convert-colors/blob/273fa68a1aecac8bf72f2dae8abeca5302d8666d/src/rgb-hsv.js#L44-L54

![image](https://user-images.githubusercontent.com/1331413/52035030-a06d8480-2564-11e9-9fa0-199eff11659c.png)

Wiki pages which are both in [Chinese](https://zh.wikipedia.org/wiki/HSL%E5%92%8CHSV%E8%89%B2%E5%BD%A9%E7%A9%BA%E9%97%B4#%E4%BB%8EHSV%E5%88%B0RGB%E7%9A%84%E8%BD%AC%E6%8D%A2) and [German](https://de.wikipedia.org/wiki/HSV-Farbraum#Umrechnung_HSV_in_RGB) are more comprehensible than the english one.

**Comment by jonathantneal** [comment]
Thank you for showing this to me. Would you review my solution at https://github.com/jonathantneal/convert-colors/pull/3 ?
